### ISSUE TITLE
RF06T02SUB01 - Figma - Telas - Módulo 1

### ISSUE THREAD

**Issue by chriskryon** [hallwaytechgrupo/ABP-2024-2#10]
- Criar a tela no Figma para o Módulo 1

**Comment by marcknero** [comment]
realizado adição do modulo 1, sem os questionários, para branch sprint-1, e adição do conteudo resumido. caso seja necessário adiciono o documento fonte de conteudo do qual retirei o resumo para o modulo.
encerrando atividade aqui no git
